//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InOutManagement.Resources.Message {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InOutManagement.Resources.Message.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 初始化成功. 的本地化字符串。
        /// </summary>
        internal static string Initialed {
            get {
                return ResourceManager.GetString("Initialed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入失败,详情请查看Log. 的本地化字符串。
        /// </summary>
        internal static string InsertError {
            get {
                return ResourceManager.GetString("InsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入失败，请检查录入数据是否正确. 的本地化字符串。
        /// </summary>
        internal static string InsertFailed {
            get {
                return ResourceManager.GetString("InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入成功. 的本地化字符串。
        /// </summary>
        internal static string InsertSuccess {
            get {
                return ResourceManager.GetString("InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检出失败,详情请查看Log. 的本地化字符串。
        /// </summary>
        internal static string OutputError {
            get {
                return ResourceManager.GetString("OutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检出失败，请检查数据是否正确. 的本地化字符串。
        /// </summary>
        internal static string OutputFailed {
            get {
                return ResourceManager.GetString("OutputFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检出成功. 的本地化字符串。
        /// </summary>
        internal static string OutputSuccess {
            get {
                return ResourceManager.GetString("OutputSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检索成功。 的本地化字符串。
        /// </summary>
        internal static string QuerySuccessful {
            get {
                return ResourceManager.GetString("QuerySuccessful", resourceCulture);
            }
        }
    }
}
